---
- hosts: first-kube-master
  remote_user: root
  tasks:
  - debug: msg="LB hosntmae is {{ lb_hostname }}"

  - name: Copy kube config file
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: /tmp/kube.config
      remote_src: yes

  - name: Inject public IP in Kube config
    ansible.builtin.lineinfile:
      path: /tmp/kube.config
      regexp: 'server:'
      line: '    server: https://{{ lb_hostname }}:6443'

  - debug: msg="Kubernetes URL is https://{{ lb_hostname }}:6443"

  - name: Fetching admin file
    fetch:
      src: /tmp/kube.config
      dest: ~/.kube/config
      flat: yes

