---
- hosts: first-kube-master
  remote_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - debug: msg="Master IP is {{ ansible_default_ipv4.address }}"

  - name: Create join statement
    shell: kubeadm token create --print-join-command
    register: join
  
  - debug: msg="Join statement is {{ join.stdout }}"

  - name: Save join
    copy:
      dest=/tmp/join
      content="{{ join.stdout }}"

  - name: Fetch token
    fetch:
      src: /tmp/join
      dest: /tmp/
      flat: yes

  - name: Remove archive file
    file:
      path: "/tmp/certs.tgz"
      state: absent

  - name: Archive certificate files
    archive:
      path: 
      - /etc/kubernetes/pki/ca*
      - /etc/kubernetes/pki/etcd_*
      - /etc/kubernetes/pki/front*
      - /etc/kubernetes/pki/sa*
      - /etc/kubernetes/pki/etcd/ca*
      - /etc/kubernetes/pki/etcd/health*
      dest: /tmp/certs.tgz
      
  - name: Fetch certificate files
    fetch:
      src: /tmp/certs.tgz
      dest: /tmp/
      flat: yes
