---
- hosts: first-kube-master
  remote_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - debug: msg="Master IP is {{ ansible_default_ipv4.address }}"

  - name: Create join statement
    shell: kubeadm token create --print-join-command
    register: join
  
  - debug: msg="Join statement is {{ join.stdout }}"

  - name: Save join
    copy:
      dest=/tmp/join
      content="{{ join.stdout }}"

  - name: Fetch token
    fetch:
      src: /tmp/join
      dest: /tmp/
      flat: yes

  - name: Copy etc/ca.crt file
    copy:
      remote_src: yes
      src: /etc/kubernetes/pki/etcd/ca.crt
      dest: /etc/kubernetes/pki/etcd_ca.crt

  - name: Fetch certificate files
    fetch:
      src: /etc/kubernetes/pki/{{ item }}
      dest: /tmp/
      flat: yes
    with_items:
      - ca.crt
      - sa.key
      - sa.pub
      - ca.key
      - front-proxy-ca.crt
      - etcd_ca.crt
