---
- hosts: first-kube-master
  remote_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - debug: msg="Master IP is {{ ansible_default_ipv4.address }}"
  - debug: msg="LB hosntmame is {{ lb_hostname }}"

  - include: kubelet.yaml

  # - name: Generate certificates and kubeconfig files
  #   shell: kubeadm init phase {{ item }} 
  #   ignore_errors: yes
  #   with_items:
  #   - certs
  #   - kubeconfig

  # - name: Write kubelet settings
  #   shell: kubeadm init phase kubelet-start --cri-socket /run/containerd/containerd.sock 
  #   ignore_errors: yes

  # - name: Initialize the master 
  #   shell: kubeadm init phase {{ item }}
  #   ignore_errors: yes
  #   with_items:
  #   - control-plane
  #   - etcd
  #   - upload-config
  #   - update-certs
  #   - mark-control-plane
  #   - bootstrap-token
  #   - kubelet-finalize
  #   - addon

  - name: Create kubeadm-config.yaml
    copy:
      dest: /tmp/kubeadm-config.yaml
      content: |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: InitConfiguration
        nodeRegistration:
          criSocket: "/var/run/dockershim.sock"
        ---
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: ClusterConfiguration
        kubernetesVersion: stable
        controlPlaneEndpoint: {{ lb_hostname }}:6443
        networking:
                podSubnet: "192.168.0.0/16"
                serviceSubnet: "192.1.0.0/16"
        etcd:
            external:
                endpoints:
                - https://{{ ansible_default_ipv4.address }}:2379
                caFile: /etc/etcd/pki/ca.crt
                certFile: /etc/etcd/pki/apiserver-etcd-client.crt
                keyFile: /etc/etcd/pki/apiserver-etcd-client.key

  - name: Pull the image
    shell: kubeadm config images pull  
    retries: 1
  
  - name: Initialize the master
    shell: kubeadm init --config /tmp/kubeadm-config.yaml --cri-socket /run/containerd/containerd.sock --upload-certs
    ignore_errors: yes
    
  - name: Install Calico operator
    shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
    ignore_errors: yes

  - name: Install Calico CNI
    shell: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
    ignore_errors: yes

  - name: Remove master taint
    shell: kubectl taint nodes --all node-role.kubernetes.io/master-
    ignore_errors: yes

  - name: Remove not-ready taint
    shell: kubectl taint nodes --all node.kubernetes.io/not-ready-
    ignore_errors: yes



