---
- hosts: other-kube-masters
  remote_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - debug: msg="Master IP is {{ ansible_default_ipv4.address }}"
  - debug: msg="join is {{ join }}"

#  - include: kubelet.yaml

  - name: Copy certificate files
    copy:
      src: /tmp/{{ item }}
      dest: /etc/kubernetes/pki/
    with_items:
      - ca.crt
      - sa.key
      - sa.pub
      - ca.key
      - front-proxy-ca.crt
      - etcd_ca.crt

  - name: Create etcd directory
    file: 
      path: /etc/kubernetes/pki/etcd
      state: directory

  - name: Copy etc/ca.crt file
    copy:
      remote_src: yes
      src: /etc/kubernetes/pki/etcd_ca.crt
      dest: /etc/kubernetes/pki/etcd/ca.crt


  - name: Initialize the masters
    shell: "{{ join }} --control-plane"


