- name: Make the Swap inactive
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab.
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Installing Prerequisites for Kubernetes
  apt: 
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - vim
      - software-properties-common
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Create directory /var/lib/apt/lists/ if it does not exist
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: directory
    mode: '0755'

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker
    mode: 0600
    validate_certs: no 
  ignore_errors: yes

- name: Install Docker Engine.
  apt: 
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add Kubernetes GPG key
  command: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes repository (Debian)
  apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      validate_certs: no 

- name: Install kubeadm
  package: name=kubeadm state=present

- name: Install kubelet
  package: name=kubelet state=present

#- name: Remove network arguments
#  replace: 
#    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#    regexp: '^(ExecStart.*)\$KUBELET_NETWORK_ARGS(.*)$'
#    replace: \1\2
#    backup: yes

- name: Install kubectl
  package: name=kubectl state=present

- name: Install kubenetes-cni
  package: name=kubernetes-cni state=present

- name: Enable docker
  shell: systemctl enable docker && systemctl start docker 

- name: Enable kubelet
  shell: systemctl enable kubelet && systemctl start kubelet

