---
- hosts: other-kube-masters
  remote_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - debug: msg="Master IP is {{ ansible_default_ipv4.address }}"
  - debug: msg="join is {{ join }}"

#  - include: kubelet.yaml

  - name: Initialize the masters
    shell: "{{ join }}"


