---
- hosts: first-kube-master
  remote_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - debug: msg="Master IP is {{ ansible_default_ipv4.address }}"
  - debug: msg="LB hosntmae is {{ lb_hostname }}"

  - include: kubelet.yaml

  - name: Initialize the master
    shell: kubeadm init --token mymymy.kubernetesssssss --apiserver-advertise-address {{ ansible_default_ipv4.address }} --pod-network-cidr=192.168.0.0/16 --cri-socket /run/containerd/containerd.sock --control-plane-endpoint {{ lb_hostname }} --upload-certs
    ignore_errors: yes

  - name: Install Calico operator
    shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
    ignore_errors: yes

  - name: Install Calico CNI
    shell: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
    ignore_errors: yes

  - name: Remove master taint
    shell: kubectl taint nodes --all node-role.kubernetes.io/master-
    ignore_errors: yes

  - name: Remove not-ready taint
    shell: kubectl taint nodes --all node.kubernetes.io/not-ready-
    ignore_errors: yes

  - name: Deploy Kube UI
    shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

  - name: Copy kube config file
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: /tmp/kube.config
      remote_src: yes

  - name: Obtain hostname
    shell: hostname
    register: hostname

  - name: Inject public IP in Kube config
    ansible.builtin.lineinfile:
      path: /tmp/kube.config
      regexp: 'server:'
      line: '    server: https://{{ lb_hostname }}:6443'

  - debug: msg="Kubernetes URL is https://{{ lb_hostname }}:6443"

  - name: Fetching admin file
    fetch:
      src: /tmp/kube.config
      dest: ~/.kube/config
      flat: yes

